/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <unistd.h>
#include "pc.h"

int sig_flag = 1;


void signal_handler(int signal_num)
{
	printf(" Catch: %d.\n", signal_num);
    sig_flag = 0;
}


void pc_prog_1(char *host, int role)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	int  service_1_arg = role;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	srand(time(NULL));

	while (sig_flag)
	{
		if (service_1_arg == 0) 
			sleep(rand() % 3 + 1);
		else
			sleep(rand() % 5 + 1);

		for (int i = 0; i < 2; i++)
        {

            retval_1 = service_1(&service_1_arg, &result_1, clnt);
            if (retval_1 != RPC_SUCCESS)
                clnt_perror(clnt, "call failed");
			else
			{
				if (service_1_arg == 0) 
					printf("Producer -> %c\n", result_1);
				else 
					printf("Consumer -> %c\n", result_1);
				break;
			}
		}
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	int role;


	if (signal(SIGINT, signal_handler) == SIG_ERR)
    {
    	perror("Can't signal:\n");
    	exit(EXIT_FAILURE);
    }

	if (argc < 3) {
		printf ("usage: %s server_host role\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	role = atoi(argv[2]);

    if (role != 0 && role != 1) {
        printf("role must be 0 or 1\n");
        exit(1);
    }

    pc_prog_1(host, role);
exit (0);
}